### ISSUE TITLE
Improve the UX of external card links

### ISSUE THREAD

**Issue by cwaring** [ipfs/ipfs-blog#213]
Currently it's not possible to distinguish external links from internal links on the blog homepage cards and it can be disorienting when these links open in a new tab. This UX is also inconsistent with the blog body content which displays a small external arrow for any outbound links.
 
![2021-05-24 at 12 29 10](https://user-images.githubusercontent.com/106938/119341518-c7977500-bc8b-11eb-9f35-52b78bf7e0d5.png)

Example from Protocol.ai

![2021-05-24 at 12 26 51](https://user-images.githubusercontent.com/106938/119341133-56f05880-bc8b-11eb-83ac-a8585d032347.png)

**Comment by jessicaschilling** [comment]
The approach most consistent with existing visual style would be simply to add the outbound-link icon to the end of the headline for cards that will open in a new window (e.g. everything but blog posts). @jdiogopeixoto, would you be able to fit this in sometime this week, since you know those cards better than anyone else? You can see it illustrated in the below screenshot: the left two cards would have the icon (since they open an off-site link) but the right card wouldn't (since it links to a blog post). Thank you!

![image](https://user-images.githubusercontent.com/1507828/119391006-0bd64580-bc8b-11eb-85cf-1c6dd605481c.png)

**Comment by jdiogopeixoto** [comment]
Yes, I'm already working on this. 

I have two questions:
1. What should we do when the text is truncated (last card below)? Should we try to fit the icon at the end?

<img width="629" alt="Screenshot 2021-05-25 at 02 13 44" src="https://user-images.githubusercontent.com/34691925/119425226-e7b44c00-bcfe-11eb-8e37-6ca103b0aacb.png">

2. Should the icon always stay in the same line where the text ends? (second card below) 

<img width="629" alt="Screenshot 2021-05-25 at 02 13 21" src="https://user-images.githubusercontent.com/34691925/119425233-eaaf3c80-bcfe-11eb-82c1-5e9d2d8b6ba6.png">

This is happening because I just added the icon to the end of the text, it works but we have those 2 issues. Let me know what you think about this so I can fix it.

**Comment by jessicaschilling** [comment]
Thanks! 
1. Yes - if the title truncates let's fit the icon at the end of the line. If that cuts down the number of characters to truncate at, that's OK. 
2. Good catch. Let's please never have a line with just an icon on it.

**Comment by cwaring** [comment]
Nice thanks! There is a utility to check external links and the icon is included as a global component too (<LinkIcon/> I think but you may need to check the src), it should be relatively simple :)
